### ISSUE TITLE
Possible bug in dereferencing options

### ISSUE THREAD

**Issue by pelov** [rockbone/p5-Net-APNS-Simple#4]
I looked at the latest changes and saw the following strange dereference:

https://github.com/rockbone/p5-Net-APNS-Simple/blob/99de51a525b076bb9edc5b77b0a03cff18b4e831/lib/Net/APNS/Simple.pm#L111

This is the first time I see this. I don't know if this will work in the latest version of perl but it doesn't work for me on perl 5.28.

**Comment by rockbone** [comment]
I'ts standard feature of Perl language I think.
Please see `perldoc perlobj`.

https://metacpan.org/pod/perlobj#Method-Names-as-Strings

Now, Net::APNS::Simple gets 100% test coverage of CPAN Testers Report. 
The test named `t/02_prepare.t` contains `prepare` method's.

https://www.cpantesters.org/distro/N/Net-APNS-Simple.html?oncpan=1&distmat=1&version=0.05&grade=2

Please report what kind of error has occurred for you.

**Comment by pelov** [comment]
Ok, I understand now - this is a method call and not a hash value look up. Learned something new today ;)
